config/routes.rb
# Update on 07/15/2019 by Zhengqi
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'users/show'

  # Routes corresponding to Post, User, Following, Like created by Yi
  resources :images
  resources :posts
  resources :relationships, only: [:create, :destroy]
  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :likes, only: [:create, :destroy]

  get 'welcome/index'
  root 'welcome#index'
  get  '/help',    to: 'welcome#help'
  get  '/about',   to: 'welcome#about'
  get  '/contact', to: 'welcome#contact'
  get  '/signup',  to: 'users#new'
  get  'users/:id', to: 'users#show', as: 'show_users'

  # Created & implemented by Pranay
	resources :posts do
	   resources :comments, only: [:create, :destroy]
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :post
belongs_to :user
validates :body, length: { maximum: 300 },    presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # Created and implemented by Pranay

  before_action :set_comment, only: [:show, :edit, :update, :destroy]



  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
   @comment = Comment.new(params.require(:comment).permit(:body, :post_id))
   @comment.user_id = current_user.id
   @time = @comment.created_at
    if @comment.save
      redirect_to "/posts/#{params[:post_id]}"
    else
      render 'new'
    end

  end


  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comments = Post.find(params[:post_id]).comments
    @comments.find(params[:id]).destroy
    redirect_to "/posts/#{params[:post_id]}"
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.permit(:user_name, :body, :idea_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%=  bootstrap_form_for @comment, url: "/posts/#{comment[:post_id]}/comments", method: "post" do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= form.text_area :body, content:nil, placeholder: "Leave a comment..."  %>

  </div>

  <%= form.hidden_field :post_id %>
  <div class="actions">
    <%= form.submit "Submit Comment", class: "btn btn-success custom" %> <!--should process show.html.erb -->
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Post Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post_id %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Idea:</strong>
  <%= @comment.idea_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>