config/routes.rb
# Update on 07/15/2019 by Zhengqi
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'users/show'

  # Routes corresponding to Post, User, Following, Like created by Yi
  resources :images
  resources :posts
  resources :relationships, only: [:create, :destroy]
  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :likes, only: [:create, :destroy]

  get 'welcome/index'
  root 'welcome#index'
  get  '/help',    to: 'welcome#help'
  get  '/about',   to: 'welcome#about'
  get  '/contact', to: 'welcome#contact'
  get  '/signup',  to: 'users#new'
  get  'users/:id', to: 'users#show', as: 'show_users'

  # Created & implemented by Pranay
	resources :posts do
	   resources :comments, only: [:create, :destroy]
  end

end

app/models/user.rb
# write the validation on 07/22/2019 by Zhengqi

# Created by Yi Implemented by Yi 
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true

  before_save { self.email = email.downcase } 
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # Associations implemented by Yi 
  has_many :active_relationships, class_name:  "Relationship",
  foreign_key: "follower_id",
  dependent:   :destroy
  has_many :passive_relationships, class_name: "Relationship",
  foreign_key: "followed_id",
  dependent: :destroy
  
  has_attached_file :avatar, styles: { medium: "300x300!", small:"200x200!", thumb: "50x50!" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :followers, through: :passive_relationships, source: :follower
  has_many :following, through: :active_relationships, source: :followed

  has_many :posts, dependent: :destroy

  has_many :active_like, class_name: "Like", foreign_key: "user_id", dependent: :destroy
  has_many :likes, through: :active_like, source: :post
  
  has_many :comments, dependent: :destroy
  
  # Helper functions to implement Follow functionality
  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  # helpers for implementing like functionalities
  def like post
    likes << post
  end
   
  def unlike post
    likes.delete post
  end

  def like? post 
    likes.include? post
  end

end

app/controllers/users_controller.rb
# Created & implemented by Yi
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  # Helper functions for following instruction implemented by Yi
  def following
    @user = User.find(params[:id])
    @followings = @user.following
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<!-- Created by Yi Implemented by Yi  -->
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
<%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit "Follow", class: "btn btn-success btn-block left-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<!-- Created by Yi Implemented by Yi  -->
<% unless current_user.id == @user.id %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<!-- Created by Yi Implemented by Yi  -->
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-success btn-block left-btn" %>
<% end %>

app/views/users/followers.html.erb
<!--write title on 07/22/2019 by Zhengqi-->
<% provide(:title, 'Followers') %>

<!-- Created by Yi Implemented by Yi  -->
<h1><%= @user.name.titleize %>'s Followers</h1>

<div class = "row">
  <div class = "col-sm-4">

      <% @followers.each do |follower| %>
      <div class = "row">
      <div class = "col-sm-2">
      <%= image_tag follower.avatar.url(:thumb), :class => "thumbnail" %>
      </div>
      <div class = "col-sm-10">
      <strong>
      <%= link_to follower.name.titleize, "/users/#{follower.id}" %>
      </strong>
        </div>
        </div>
      <% end %>
    
  </div>
  </div>

app/views/users/following.html.erb
<!--write title on 07/22/2019 by Zhengqi-->
<% provide(:title, 'Followings') %>

<!-- Created by Yi Implemented by Yi  -->
<h1><%= @user.name.titleize %>'s Followings</h1>

<div class = "row">
  <div class = "col-sm-4">

      <% @followings.each do |following| %>
      <div class = "row">
      <div class = "col-sm-2">
      <%= image_tag following.avatar.url(:thumb), :class => "thumbnail" %>
      </div>
      <div class = "col-sm-10">
      <strong>
      <%= link_to following.name.titleize, "/users/#{following.id}" %>
      </strong>
        </div>
        </div>
      <% end %>
    
  </div>
  </div>

app/views/users/show.html.erb
<!--write the title on 07/22/2019 by Zhengqi-->
<% provide(:title, @user.name) %>

<!-- Created by Yi Implemented by Yi  -->
<% if !user_signed_in? %>
  <div class="center jumbotron">
    <h1><span class = "glyphicon glyphicon-camera" area-hidden="ture"></span> Freelance Canvas</h1>
    <h2>Please log in to unlock more functionalities! </h2>
    <h2>
      This is the home page for the
      <a href="#">Freelance Canvas Project</a>
       created by TYP-HD
    </h2>
    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-primary" %>
  </div>
<% else %>
  <div class = "row" id="profile-card">

    <div class="col-md-12 col-sm-12 profile-wall">
      <div class="col-sm-12">
        <div class="col-xs-12 col-sm-8">
          <div class = "row">
            <div class="col-sm-8">
              <h1 id = "profile-name"><%= @user.name.titleize %>
                <h1 id = "profile-bt">
                  <% if (current_user.id == @user.id) %>
                    <button  class= "btn btn-success  left-btn",
                      onclick="window.location.href = '<%= edit_user_registration_path%>';">
                          Edit Profile 
                    </button>
                  <% end %>
                  <%= render 'follow_form' if user_signed_in? %>
                </h1>
              </h1>
            </div>
          </div>

          <p><strong>Email: </strong><%= @user.email %></p>
          <p><strong>Bio: </strong> <%= (@user.bio == "")||(@user.bio == nil) ? "Didn't say anything yet." : @user.bio %> </p>
            
        </div>             
        <div class="col-xs-12 col-sm-4 ">
          <%= image_tag @user.avatar.url(:small), :class => "thumbnail"%>
        </div>
      </div>

      <div class="col-xs-12 divider text-center">
          <div class="col-xs-12 col-sm-4 emphasis">
            <a href="<%= followers_user_path(@user) %>">
              <h2><strong id="followers"><%= @user.followers.count %></strong></h2>                    
              <p><small>Followers</small></p>
            </a> 
          </div>
          <div class="col-xs-12 col-sm-4 emphasis">
            <a href="<%= following_user_path(@user) %>">
              <h2><strong><%= @user.following.count %></strong></h2>                    
              <p><small>Following</small></p>
            </a>
          </div>
          <div class="col-xs-12 col-sm-4 emphasis">
            <a href="<%= posts_path %>">
              <h2><strong><%= @user.posts.count %></strong></h2>                    
              <p><small>Posts</small></p>
            </a>
          </div>
      </div>
    </div>                 
  </div>

  <div class = "row">
    <% @user.posts.each do |post| %> 
      <div class="col-md-4 col-sm-6">
          <div class="hovereffect">
            <%= image_tag post.image.url(:medium), class: "img-responsive" %>
            <div class="overlay">
              <h2><span class="glyphicon glyphicon-thumbs-up"></span>   <%= post.likes.count %></h2>
              <% if current_user.id == @user.id %>
              <%= link_to 'Edit', edit_post_path(post), class: "info" %>
              <% end %>
              <%= link_to "Check Detail", post_path(post), class: "info" %>
            </div>
          </div>
      </div>
    <% end %>
  </div>


<% end%>