config/routes.rb
# Update on 07/15/2019 by Zhengqi
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'users/show'

  # Routes corresponding to Post, User, Following, Like created by Yi
  resources :images
  resources :posts
  resources :relationships, only: [:create, :destroy]
  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :likes, only: [:create, :destroy]

  get 'welcome/index'
  root 'welcome#index'
  get  '/help',    to: 'welcome#help'
  get  '/about',   to: 'welcome#about'
  get  '/contact', to: 'welcome#contact'
  get  '/signup',  to: 'users#new'
  get  'users/:id', to: 'users#show', as: 'show_users'

  # Created & implemented by Pranay
	resources :posts do
	   resources :comments, only: [:create, :destroy]
  end

end

app/models/post.rb
class Post < ApplicationRecord
  # Created by Yi Implemented by Yi 
  has_attached_file :image, styles: {large: "1000x600#", medium: "500x300#", small: "100x100#"}, default_url: "/images/:style/missingPost.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_presence_of :image_file_size
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :passive_like, class_name: "Like", foreign_key: "post_id", dependent: :destroy
  has_many :likes, through: :passive_like, source: :user



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # Created & implemented by Yi
  
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  

  # GET /posts
  # GET /posts.json
  def index
    @user =  User.find(current_user.id)
    @posts = @user.posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
@comments = Post.find(params[:id]).comments.all
#Post.find(params[:id]).comments.all
#Post.first.comments
@comment = Post.find(params[:id]).comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<!-- Created by Yi Implemented by Yi  -->

<div class="row">
  <div class="col-md-6 col-md-offset-3" >

    <%= form_for @post, html: { multipart: true } do |form| %>

    <% if post.errors.any? %>
      <div class="alert alert-danger" role="alert">
            <% post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title , class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_field :content, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image , class: 'form-control'%>
    </div>

    <div class="actions">
      <%= form.submit "Submit",class:"btn btn-primary" %>
    </div>

    <% end %>

  </div>
</div>

app/views/posts/_like.html.erb
<!-- Created by Yi Implemented by Yi  -->
<%= form_for(current_user.active_like.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :post_id, @post.id %></div>
  <%= f.submit "Like", class: "btn btn-primary" %>
<% end %>

app/views/posts/_like_form.html.erb
  <!-- Created by Yi Implemented by Yi  -->
  
  <% if current_user != nil%>
    <div id="like_form">
    <% if current_user.like?(@post) %>
      <%= render 'unlike' %>
    <% else %>
      <%= render 'like' %>
    <% end %>
    </div>
  <% end %>

app/views/posts/_unlike.html.erb
<!-- Created by Yi Implemented by Yi  -->
<%= form_for(current_user.active_like.find_by(post_id: @post.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unlike", class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<!--write title on 07/22/2019 by Zhengqi-->
<% provide(:title, 'Edit Post') %>

<!-- Created by Yi Implemented by Yi  -->
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<div class = "container">
<%= link_to 'Delete This Masterpiece', @post, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger'%> 

</div>

app/views/posts/index.html.erb
<!--write on 07/22/2019 by Zhengqi-->
<% provide(:title, 'Post') %>

<!-- Created by Yi Implemented by Yi  -->
<div class = "center jumbotron">
  <h1>Gallery of Your Masterpieces</h1>
  <h2>M A S T E R P I E C E S</h2>
  <%= link_to 'New Post', new_post_path , class: "btn btn-lg btn-success" ,id:"light"%>
</div>


<div class = "row">
  <% @posts.each do |post| %> 
    <div class="col-md-4 col-sm-6">
        <div class="hovereffect">
          <%= image_tag post.image.url(:medium), class: "img-responsive" %>
          <div class="overlay">
            <h2><span class="glyphicon glyphicon-thumbs-up"></span>  <%= post.likes.count %></h2>
            <%= link_to 'Edit', edit_post_path(post), class: "info" %>
            <%= link_to "Check Detail", post_path(post), class: "info" %>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<!--write title on 07/22/2019 by Zhengqi-->
<% provide(:title, 'New Post') %>
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<!--write title on 07/22/2019 by Zhengqi-->
<% provide(:title, 'Show Post') %>

<!-- Created by Yi Implemented by Yi  -->
<div class="col-md-12">
<div class="thumbnail">
<%= image_tag @post.image.url(:large) , id: "main-image"%>
</div></div>
<div class = "container">
<div class = "row">
  <div class = "col-md-8" >
      <p><span class="glyphicon glyphicon-heart"></span>
      <strong>Likes: </strong>
        <span id="likes"><%= @post.likes.count %></span></p>
      <p>
        <span class="glyphicon glyphicon-user"></span>
        <strong>Author: </strong>
        <%= link_to User.find(@post.user_id).name.titleize, user_path(User.find(@post.user_id)) %>
      </p>

      <p>
        <span class="glyphicon glyphicon-subtitles"></span>
        <strong>Title: </strong>
        <%= @post.title %>
      </p>

      <p>
        <span class="glyphicon glyphicon-comment"></span>
        <strong>Content:</strong>
        <%= @post.content %>
      </p>
</div>

  
<div class = "col-md-1">
    <%= render 'like_form' if user_signed_in? %>
  </div>

  <div class = "col-md-1">
      <% if current_user.id == @post.user_id %>
        <%= link_to 'Edit', edit_post_path(@post) , class:'btn btn-success' , id:"btn-light"%> 
      <% end %> 
  </div>
  <div class = "col-md-1">
    <%= link_to "More", user_path(User.find(@post.user_id)), class:"btn btn-primary" , id:"btn-light" %>
  </div>
     
  

</div>

<h3>Write Comments</h3>

<%= render partial: 'comments/form', locals: { comment: @comment } if user_signed_in? %>

<h3>User Comments</h3>
<br />
<% @comments.each do |comment| %>

<div class="container">


<div class="row">
<div class="col-sm-12">
</div>
</div>
<div class="row">
  <div class="col-sm-1">
    <div class="thumbnail">
      <%= image_tag User.find(comment.user_id).avatar.url(:small), :class => "img-responsive user-photo" %>
    </div>
  </div>

  <div class="col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong><%= User.find(comment.user_id).name.titleize %></strong> <span class="text-muted">commented on <%= comment.created_at %></span>
      </div>
      <div class="panel-body">
        <%= comment.body %>
      </div>
    </div>
  </div>


   <% if comment.user_id == current_user.id || current_user.id == @post.user_id %>
  <div class="col-sm-1">
  <%= button_to 'Delete', "/posts/#{params[:id]}/comments/#{comment.id}", method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-warning" %>
  </div>
  <% end %>


</div>

</div>

<% end %>