config/routes.rb
# Update on 07/15/2019 by Zhengqi
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'users/show'

  # Routes corresponding to Post, User, Following, Like created by Yi
  resources :images
  resources :posts
  resources :relationships, only: [:create, :destroy]
  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :likes, only: [:create, :destroy]

  get 'welcome/index'
  root 'welcome#index'
  get  '/help',    to: 'welcome#help'
  get  '/about',   to: 'welcome#about'
  get  '/contact', to: 'welcome#contact'
  get  '/signup',  to: 'users#new'
  get  'users/:id', to: 'users#show', as: 'show_users'

  # Created & implemented by Pranay
	resources :posts do
	   resources :comments, only: [:create, :destroy]
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">

 
    <%= link_to "Back", :back %> |
    The <a href="https://web.500px.com/">Freelance Canvas Project</a>
    by <a href="http://web.cse.ohio-state.edu/~shareef.1/3901.su19/labs/project6.shtml">TYP-HD</a>


    <ul>
<%= link_to "About",   about_path %> |
<%= link_to "Contact", contact_path %> | 
<a href="http://web.cse.ohio-state.edu/~shareef.1/3901.su19/labs/project6.shtml">TYP-HD</a>
    </ul>

</footer>

app/views/layouts/_head.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <!-- it ensures some old browser will work as well -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-nav-demo">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
      <a href="/" class="navbar-brand"><span class="glyphicon glyphicon-picture"></span> TYP-HD</a>
    </div>
    <div class="collapse navbar-collapse" id = "bs-nav-demo">
    <ul class="nav navbar-nav">
					<li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "Help",   help_path %></li>
				</ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "My Posts", posts_path, :class => 'navbar-link'%>
        <li><%= link_to "Profile",  "/users/#{current_user.id}" %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path  %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Freelance Canvas</title>
  </head>
    <%=render 'layouts/head' %>
  </head>
  <body>
  <!-- It's yielding a block -->
    <%= render 'layouts/header' %>
    <% if notice %>
    <div class="alert alert-success" role="alert">
    <p class="notice"><%= notice %></p>
    </div>
    <% end %>
    <% if alert %>
    <div class="alert alert-danger" role="alert">
    <p class="alert"><%= alert %></p>
    </div>
    <% end %>
    <div class="container">
      <%= yield %>
      <%=render 'layouts/footer' %>
      <!--For debugging. It creates a debugging window-->

    </div>
  </body>
</html>